server:
  port: 9090

spring:
  application:
    name: movie-server
  profiles:
    active: dev
  datasource:
    driver-class-name: ${movie.datasource.driver-class-name}
    name: movie
    url: jdbc:mysql://${movie.datasource.host}:${movie.datasource.port}/${movie.datasource.database}
    username: ${movie.datasource.username}
    password: ${movie.datasource.password}
  data:
    redis:
      host: ${movie.redis.host}
      port: ${movie.redis.port}
      database: ${movie.redis.database}
  mail:
    host: ${movie.mail.host}
    port: ${movie.mail.port}
    username: ${movie.mail.username}
    password: ${movie.mail.password}
    protocol: ${movie.mail.protocol}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      samgoldsee:
        movie:
          mapper: debug
          service: info
          controller: info

aliyun:
  oss:
    endpoint: ${movie.aliyun.endpoint}
    access-key-id: ${movie.aliyun.key-id}
    access-key-secret: ${movie.aliyun.key-secret}
    bucket-name: ${movie.aliyun.bucket-name}

alipay:
  app_id: ${movie.alipay.appId}
  merchant_private_key: ${movie.alipay.merchant_private_key}
  alipay_public_key: ${movie.alipay.alipay_public_key}
  notify_url: ${movie.alipay.notify_url}
  return-url: ${movie.alipay.return_url}
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
