movie:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: movie
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
  mail:
    host: smtp.163.com
    port: 465
    username: SGSMovie@163.com
    password: NUsfnQUqNpexMQGB
    protocol: smtp