-- 插入电影类型数据
INSERT INTO `movie_type` (`name`)
VALUES ('动作'),
       ('喜剧'),
       ('剧情'),
       ('科幻'),
       ('恐怖'),
       ('爱情'),
       ('悬疑'),
       ('动画'),
       ('历史'),
       ('战争'),
       ('奇幻'),
       ('冒险'),
       ('纪录片'),
       ('家庭'),
       ('犯罪'),
       ('音乐'),
       ('武侠'),
       ('古装'),
       ('其他');

-- 插入电影地区数据
INSERT INTO `movie_zone` (`name`)
VALUES ('内地'),
       ('中国香港'),
       ('中国台湾'),
       ('美国'),
       ('韩国'),
       ('日本'),
       ('欧洲'),
       ('印度'),
       ('泰国'),
       ('其他');

-- 插入用户账号数据
INSERT INTO `user` (name, email, password, gender, type, avatar, create_time, update_time)
VALUES ('SamGoldSee1', '2377043893@qq.com', '$2a$10$a4IqEdp3neRXuKeU65NJyOD0eNO2v/gRJ0t1JTl0gFBhBYUJitcte', 'M', '0',
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/user/2025-05-26-2377043893.png',
        '2025-05-21 14:44:51', '2025-05-22 11:26:17'),
       ('SamGoldSee2', 'chunxin.huang@m.scnu.edu.cn', '$2a$10$HhodoGa30zWI0N5c2aZNHOeyyAQjxJvTL2pS2hwrNryY1ZRUt2k8u',
        'M', '1', '', '2025-05-22 11:58:50', '2025-05-22 11:58:50');

-- 插入电影数据
INSERT INTO `movie` (name, description, zone_id, view, poster, permission, release_date)
VALUES ('让子弹飞', '张麻子冒充县长与地方恶霸黄四郎斗智斗勇，一场融合黑色幽默与江湖义气的较量。', 1, 659000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/1.jpeg', 1,
        '2010-12-16'),
       ('流浪地球', '地球即将被太阳吞没，人类建造推进器将地球推出太阳系，开启史诗般的星际迁移。', 1, 4670000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/2.jpeg', 0,
        '2019-02-05'),
       ('我不是药神', '一位代购慢粒白血病药的平民揭露医疗体制与人性挣扎，改编自真实事件。', 1, 3100000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/3.jpeg', 1,
        '2018-07-05'),
       ('无间道', '一位警方卧底与一名黑帮卧底各自隐藏身份，命运在正邪之间交错激荡。', 2, 55050000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/4.jpeg', 0, '2002-12-12'),
       ('英雄本色', '兄弟情、黑道恩怨与牺牲交织，标志性的“我要吃饭”台词成为一代经典。', 2, 34000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/5.jpeg', 1, '1986-08-02'),
       ('重庆森林', '讲述两个孤独警察的爱情故事，王家卫式浪漫下藏着都市异化与情感漂流。', 2, 600200,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/6.jpeg', 0, '1994-07-14'),
       ('海角七号', '一个邮差无意间收到的日本情书串联起两代人的爱情与梦想，充满乡土与青春气息。', 3, 300000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/7.jpeg', 1,
        '2008-08-22'),
       ('那些年，我们一起追的女孩', '校园爱情故事引发观众集体怀旧，刻画青春中的懵懂与遗憾。', 3, 76461000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/8.jpeg', 0,
        '2011-08-19'),
       ('艋舺', '聚焦台北黑帮少年的成长与背叛，是对江湖义气与青春梦想的反思。', 3, 250000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/9.jpeg', 1, '2010-02-05'),
       ('盗梦空间', '多层梦境叠加中执行植入任务，融合心理学、动作与科幻元素，构建复杂世界观。', 4, 870000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/10.jpeg', 1,
        '2010-07-16'),
       ('复仇者联盟4：终局之战', '超级英雄集结对抗灭霸，划时代的漫威宇宙收官之作，情怀与视觉的双重高潮。', 4, 2798000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/11.jpeg', 0,
        '2019-04-26'),
       ('肖申克的救赎', '银行家被冤入狱，凭借希望与智慧最终越狱重生，象征人类对自由的追寻。', 4, 58300000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/12.jpeg', 1,
        '1994-09-23'),
       ('寄生虫', '底层家庭逐步取代上层家庭职位，讽刺阶级分化，获得奥斯卡最佳影片。', 5, 130700000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/13.jpeg', 0, '2019-05-30'),
       ('熔炉', '揭露真实校园性侵案件，引发韩国法律改革，直面人性与制度黑暗。', 5, 35000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/14.jpeg', 1, '2011-09-22'),
       ('辩护人', '改编自卢武铉律师生涯，讲述一位税务律师因人权案件转型为社会正义斗士。', 5, 83000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/15.jpeg', 0, '2013-12-18'),
       ('千与千寻', '少女误入神灵世界，在成长中拯救父母，是宫崎骏动画的巅峰之作。', 6, 395800000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/16.jpeg', 1, '2001-07-20'),
       ('你的名字。', '男女主角灵魂互换并穿越时间，展开一段唯美而哀伤的恋爱奇遇。', 6, 380000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/17.jpeg', 0, '2016-08-26'),
       ('小森林：夏秋篇', '都市女子回归乡村自耕自食，疗愈系电影展现人与自然的宁静共处。', 6, 12000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/18.jpeg', 1, '2014-08-30'),
       ('放牛班的春天', '音乐感化问题少年，讲述爱与教育的力量，感动无数观众。', 7, 83000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/19.jpeg', 0, '2004-03-17'),
       ('这个杀手不太冷', '杀手与小女孩在冷酷城市中建立温情关系，动作与情感并存。', 7, 45000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/20.jpeg', 1, '1994-09-14'),
       ('天堂电影院', '一个男孩与放映师的友情串联起意大利电影发展的诗意回忆。', 7, 12000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/21.jpeg', 0, '1988-11-17'),
       ('摔跤吧！爸爸', '印度父亲训练女儿成为摔跤冠军，传递女性觉醒与家庭梦想。', 8, 300000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/22.jpeg', 1, '2016-12-21'),
       ('三傻大闹宝莱坞', '大学生活、教育制度批判与友情交织而成的印度高分喜剧。', 8, 202000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/23.jpeg', 0, '2009-12-25'),
       ('我的名字叫可汗', '一位自闭症穆斯林在美国寻找认同与和平，融合种族与宗教议题。', 8, 220000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/24.jpeg', 1, '2010-02-12'),
       ('天才枪手', '天才学生设计作弊计划，智斗全球考试制度，节奏紧张如动作片。', 9, 44000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/25.jpeg', 0, '2017-05-03'),
       ('初恋这件小事', '平凡少女默默爱慕学长的故事，唤起青春期的甜酸滋味。', 9, 79000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/26.jpeg', 1, '2010-08-12'),
       ('你好，陌生人', '两个陌生人在菲律宾旅行中逐渐建立起微妙感情，是浪漫系代表作。', 9, 15000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/27.jpeg', 0, '2010-08-19'),
       ('摩托日记', '根据切·格瓦拉旅行笔记改编，记录拉美青年在摩托之旅中觉醒社会责任。', 10, 57000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/28.jpeg', 1, '2004-01-15'),
       ('帝企鹅日记', '纪录南极帝企鹅艰难孵育过程，展现自然界的生命奇迹与亲情伟大。', 10, 77000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/29.jpeg', 0, '2005-01-26'),
       ('华氏911', '迈克尔·摩尔执导的纪录片，批判布什政府对911事件及伊拉克战争的应对。', 10, 220000000,
        'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/movie/30.jpeg', 1, '2004-06-25');

-- 插入导演数据
INSERT INTO `director`(name, avatar, description)
VALUES ('姜文', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/1.jpeg',
        '中国大陆著名导演，演员。代表作《阳光灿烂的日子》、《让子弹飞》、《鬼子来了》。第33届金马奖最佳导演奖得主。'),
       ('郭帆', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/2.jpeg',
        '中国大陆电影导演、编剧及监制。代表作《同桌的你》、《流浪地球》。荣获35届大众电影百花奖最佳导演奖。'),
       ('文牧野', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/3.jpeg',
        '中国内地影视导演、编剧。代表作《我不是药神》、《我和我的祖国》。第55届台湾电影金马奖最佳新导演奖得主'),
       ('刘伟强', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/4.jpeg',
        '中国香港华语影视导演、摄影师。代表作《无间道》、《中国机长》。荣获第40届金马奖最佳导演奖'),
       ('吴宇森', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/5.jpeg',
        '中国香港男导演、编剧、演员、监制、制片人。代表作《英雄本色》、《喋血双雄》。第9届金像奖最佳导演奖、得主'),
       ('王家卫', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/6.jpeg',
        '中国大陆华语影视男导演、编剧、制片人。代表作《重庆森林》、《花样年华》、《一代宗师》。第50届戛纳国际电影节最佳导演奖得主'),
       ('魏德圣', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/7.jpeg',
        '中国台湾男导演。代表作《海角七号》。荣获第4届中国电影导演协会年度港台导演奖，金马奖台湾杰出电影工作者'),
       ('九把刀', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/8.jpeg',
        '本名柯景腾，中国台湾网络作家、导演、编剧、监制。代表作《那些年，我们一起追的女孩》。提名第48届金马奖最佳新导演奖'),
       ('钮承泽', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/9.jpeg',
        '中国台湾男演员、导演、戏剧制作人。代表作《艋舺》。荣获第11届华语电影传媒大奖最佳新导演。2018年12月，在拍摄电影《跑马》剧组期间被指控涉嫌性侵，被依法判刑4年徒刑定谳'),
       ('克里斯托弗·诺兰', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/10.jpeg',
        '英国导演、编剧、制片人。代表作《盗梦空间》、《星际穿越》、《敦刻尔克》、《奥本海默》。第81届金球奖最佳导演、第96届奥斯卡金像奖最佳导演奖得主'),
       ('安东尼·罗素', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/11.jpeg',
        '美国导演、编剧、制作人。代表作《复仇者联盟3：无限战争》、《复仇者联盟4：终局之战》。荣获第56届艾美奖喜剧类剧集-喜剧类剧集最佳导演奖'),
       ('弗兰克·德拉邦特', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/12.jpeg',
        '法国导演、编剧、制片人。代表作《肖申克的救赎》、《行尸走肉第一季》、《哥斯拉》。提名第26届，第34届土星奖-最佳导演奖'),
       ('奉俊昊', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/13.jpeg',
        '韩国导演、编剧。代表作《寄生虫》、《雪国列车》。第92届奥斯卡金像奖最佳导演奖、第72届戛纳国际电影节主竞赛单元-金棕榈奖得主'),
       ('黄东赫', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/14.jpeg',
        '韩国导演、编剧、制作人。代表作《熔炉》、《鱿鱼游戏》。提名第38届韩国青龙电影奖最佳导演奖、第55届韩国电影大钟奖最佳导演奖'),
       ('杨宇硕', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/15.jpeg',
        '韩国首尔，韩国导演、编剧。代表作《辩护人》、《铁雨》。荣获第51届韩国电影大钟奖最佳新人导演奖'),
       ('宫崎骏', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/16.jpeg',
        '日本动画师、动画制作人、漫画家、动画导演、动画编剧。代表作《千与千寻》、《风之谷》、《龙猫》。第52届柏林国际电影节金熊奖、第87届奥斯卡金像奖终身成就奖得主'),
       ('新海诚', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/17.jpeg',
        '日本动画导演、编剧、漫画作家。代表作《你的名字。》、《言叶之庭》、《秒速5厘米》。荣获第26届日本电影评论家大奖导演奖'),
       ('森淳一', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/18.jpeg',
        '日本导演、编剧。代表作《小森林夏秋篇》、《小森林冬春篇》。荣获第16届圣丹斯电影节日本放送协会奖'),
       ('克里斯托夫·巴拉蒂', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/19.jpeg',
        '法国导演、编剧、制作人。代表作《放牛班的春天》。提名第77届奥斯卡金像奖最佳外语片奖'),
       ('吕克·贝松', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/20.jpeg',
        '法国男导演、制片人、编剧、演员。代表作《这个杀手不太冷》、《亚特兰蒂斯》、《超体》。第23届法国电影凯撒奖最佳导演奖得主'),
       ('朱塞佩·托纳多雷', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/21.jpeg',
        '意大利导演、编剧。代表作《天堂电影院》、《西西里的美丽传说》。第62届奥斯卡金像奖最佳外语片奖、第42届戛纳国际电影节评审团大奖得主'),
       ('尼特什·提瓦瑞', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/22.jpeg',
        '印度导演、编剧、制片人。代表作《摔跤吧！爸爸》、《最初的梦想》。荣获第62届印度电影观众奖最佳导演奖'),
       ('拉库马·希拉尼', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/23.jpeg',
        '印度导演、编剧、制作人、剪辑师。代表作《三傻大闹宝莱坞》、《我的个神啊》。第13届亚洲电影大奖最佳导演奖得主'),
       ('卡伦·乔哈尔', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/24.jpeg',
        '印度制片、编剧、导演、演员、服装设计。代表作《我的名字叫可汗》、《年度最佳学生》'),
       ('纳塔吾·彭皮里亚', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/25.jpeg',
        '泰国电影导演、编剧。代表作《天才枪手》。荣获第22届泰国电影金天鹅奖最佳剧本奖、第12届亚洲电影大奖最佳编剧奖'),
       ('普特鹏·普罗萨卡·那·萨克那卡林', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/26.jpeg',
        '泰国导演、编剧和演员。代表作《初恋这件小事》、《想爱就爱》'),
       ('班庄·比辛达拿刚', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/27.jpeg',
        '泰国导演、编剧。代表作《你好，陌生人》、《死神的十字路口》。荣获第23届泰国电影金天鹅奖最佳导演奖'),
       ('沃尔特·塞勒斯', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/28.jpeg',
        '巴西电影导演、编剧、制片人。代表作《摩托日记》、《越位》。第48届柏林国际电影节金熊奖、第56届美国电影电视金球奖最佳外语片奖得主'),
       ('吕克·雅克', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/29.jpeg',
        '法国著名导演、编剧及摄影师，以自然题材纪录片和剧情片著称。代表作《帝企鹅日记》'),
       ('迈克尔·摩尔', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/director/30.jpeg',
        '美国作家、演员、编剧、导演。代表作《华氏911》、《资本主义：一个爱情故事》。第57届戛纳国际电影节金棕榈奖、第75届奥斯卡金像奖最佳纪录片奖得主');

-- 插入导演-电影数据
INSERT INTO `director-movie`(director_id, movie_id)
VALUES (1, 1),
       (2, 2),
       (3, 3),
       (4, 4),
       (5, 5),
       (6, 6),
       (7, 7),
       (8, 8),
       (9, 9),
       (10, 10),
       (11, 11),
       (12, 12),
       (13, 13),
       (14, 14),
       (15, 15),
       (16, 16),
       (17, 17),
       (18, 18),
       (19, 19),
       (20, 20),
       (21, 21),
       (22, 22),
       (23, 23),
       (24, 24),
       (25, 25),
       (26, 26),
       (27, 27),
       (28, 28),
       (29, 29),
       (30, 30);

-- 插入演员数据
INSERT INTO `actor` (name, avatar, description)
VALUES ('姜文', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/1.jpeg',
        '中国影坛硬汉代表，兼具导演才华，擅长塑造独特角色。'),
       ('吴京', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/2.jpeg',
        '动作明星，军旅背景出身，致力打造中国科幻新高峰。'),
       ('徐峥', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/3.jpeg',
        '实力派演员兼导演，擅长现实题材的深刻演绎。'),
       ('梁朝伟', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/4.jpeg',
        '香港影帝，擅长演绎内心戏，沉稳而细腻。'),
       ('周润发', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/5.jpeg',
        '枪火美学代表人物，经典黑帮形象深入人心。'),
       ('金城武', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/6.jpeg',
        '日台混血男神，气质忧郁，王家卫御用演员。'),
       ('范逸臣', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/7.jpeg',
        '台湾歌手转型演员，凭此片一跃成名。'),
       ('陈妍希', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/8.jpeg',
        '台湾女演员，以清新形象著称，诠释青春懵懂与纯真情感。'),
       ('阮经天', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/9.jpeg',
        '金马奖影帝，塑造台北少年帮派的兄弟情义。'),
       ('莱昂纳多·迪卡普里奥', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/10.jpeg',
        '好莱坞巨星，演技层次丰富，角色深入人心。'),
       ('小罗伯特·唐尼', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/11.jpeg',
        '演绎钢铁侠长达十年，定义漫威宇宙灵魂。'),
       ('蒂姆·罗宾斯', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/12.jpeg',
        '性格演员，以优雅沉稳塑造信仰与希望。'),
       ('宋康昊', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/13.jpeg',
        '韩国殿堂级演员，长年活跃影坛，角色多样精湛。'),
       ('孔刘', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/14.jpeg',
        '韩国知性派男星，突破偶像形象，关注社会议题。'),
       ('柊瑠美', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/16.jpeg',
        '声线自然亲切，细腻展现千寻从懵懂到坚强的变化。'),
       ('上白石萌音', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/17.jpeg',
        '声音清新动人，细腻诠释少女复杂情感。'),
       ('桥本爱', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/18.jpeg',
        '日本文艺女演员，代表乡村治愈系生活电影风格。'),
       ('热拉尔·朱诺', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/19.jpeg',
        '法国演员，温柔坚定的音乐老师形象深入人心。'),
       ('让·雷诺', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/20.jpeg',
        '法国硬汉演员，冷酷与温情并存的杀手代表。'),
       ('菲利普·努瓦雷', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/21.jpeg',
        '资深法国演员，饰演温情放映师，情感细腻动人。'),
       ('阿米尔·汗', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/22.jpeg',
        '印度影坛良心，塑造坚毅父亲，展现女性觉醒。'),
       ('沙鲁克·汗', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/23.jpeg',
        '印度浪漫影帝，本片中塑造自闭穆斯林令人动容。'),
       ('茱蒂蒙·琼查容苏因', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/24.jpeg',
        '模特转型演员，以聪慧冷静形象惊艳亚洲影坛。'),
       ('平采娜·乐维瑟派布恩', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/25.jpeg',
        '泰国人气女星，以清新自然形象俘获观众。'),
       ('恩充·迪伊', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/26.jpeg',
        '菲律宾演员，气质儒雅，诠释异国旅途中的情感变化。'),
       ('盖尔·加西亚·贝纳尔', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/27.jpeg',
        '墨西哥演员，演绎切·格瓦拉的革命觉醒之旅。'),
       ('帝企鹅', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/28.jpeg',
        '南极严寒下的孵化与生存奇迹，展现生命的伟大。'),
       ('迈克尔·摩尔', 'https://sgs-movie-oss.oss-cn-guangzhou.aliyuncs.com/actor/29.jpeg',
        '美国纪录片导演，以犀利批判风格著称，揭露政治内幕。');

-- 插入演员-电影数据
INSERT INTO `actor-movie` (actor_id, movie_id)
VALUES (1, 1),
       (2, 2),
       (3, 3),
       (4, 4),
       (5, 5),
       (6, 6),
       (7, 7),
       (8, 8),
       (9, 9),
       (10, 10),
       (11, 11),
       (12, 12),
       (13, 13),
       (14, 14),
       (13, 15),
       (15, 16),
       (16, 17),
       (17, 18),
       (18, 19),
       (19, 20),
       (20, 21),
       (21, 22),
       (21, 23),
       (22, 24),
       (23, 25),
       (24, 26),
       (25, 27),
       (26, 28),
       (27, 29),
       (28, 30);

-- 插入电影-电影类型数据
INSERT INTO `movie-movie_type`(movie_id, type_id)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (2, 4),
       (2, 12),
       (2, 3),
       (3, 3),
       (3, 15),
       (4, 15),
       (4, 7),
       (4, 3),
       (5, 15),
       (5, 3),
       (6, 6),
       (6, 3),
       (7, 6),
       (7, 3),
       (8, 6),
       (8, 3),
       (8, 2),
       (9, 15),
       (9, 3),
       (10, 4),
       (10, 12),
       (10, 7),
       (11, 1),
       (11, 4),
       (11, 12),
       (12, 3),
       (13, 3),
       (13, 7),
       (14, 3),
       (14, 9),
       (15, 3),
       (15, 9),
       (16, 8),
       (16, 12),
       (16, 11),
       (17, 8),
       (17, 6),
       (17, 11),
       (18, 3),
       (18, 14),
       (19, 3),
       (19, 16),
       (20, 1),
       (20, 3),
       (21, 3),
       (21, 16),
       (22, 3),
       (22, 6),
       (22, 9),
       (23, 3),
       (23, 2),
       (24, 3),
       (24, 9),
       (25, 7),
       (25, 2),
       (25, 3),
       (26, 6),
       (26, 3),
       (27, 6),
       (27, 3),
       (28, 13),
       (28, 3),
       (29, 13),
       (29, 14),
       (30, 13),
       (30, 15);